[workspace]
authors = ["b1aha <jiriblahaa@outlook.cz>"]
channels = ["conda-forge"]
name = "eclipse"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
test      = "pytest"
typecheck = "mypy"

[pypi-dependencies]
eclipse = { path = ".", editable = true }

[dependencies]
python = ">=3.12,<3.13"
numpy = ">=2.5.1,<3"
scipy = ">=1.18.0,<2"
matplotlib = ">=3.11.1,<4"
pyyaml = ">=6.0.3,<7"
pytest = ">=9.1.1,<10"
mypy = ">=2.3.0,<3"
